Repository dotnet/diagnostics, pull requests merged in 2019-12, with the labels that each got.

#668 Upgrade to latest System.CommandLine version
  diagnostics.sln
  eng/Versions.props
  src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
  src/Tools/Common/CommandExtensions.cs
  src/Tools/Common/CommandLineException.cs
  src/Tools/Common/Commands/ProcessStatus.cs
  src/Tools/Common/ConsoleCancellation.cs
  src/Tools/Common/DebugUtil.cs
  src/Tools/dotnet-counters/Program.cs
  src/Tools/dotnet-counters/dotnet-counters.csproj
  src/Tools/dotnet-dump/Analyzer.cs
  src/Tools/dotnet-dump/Commands/SOSCommand.cs
  src/Tools/dotnet-dump/Program.cs
  src/Tools/dotnet-dump/dotnet-dump.csproj
  src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
  src/Tools/dotnet-gcdump/CommandLine/ProcessStatusCommandHandler.cs
  src/Tools/dotnet-gcdump/Program.cs
  src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
  src/Tools/dotnet-sos/Program.cs
  src/Tools/dotnet-sos/dotnet-sos.csproj
  src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
  src/Tools/dotnet-trace/CommandLine/Commands/ConvertCommand.cs
  src/Tools/dotnet-trace/CommandLine/Commands/ListProcessesCommandHandler.cs
  src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
  src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
  src/Tools/dotnet-trace/Program.cs
  src/Tools/dotnet-trace/dotnet-trace.csproj
Labels: diagnostic global tooling

#690 Fix various issues
  documentation/lldb/linux-instructions.md
  documentation/sos-debugging-extension-windows.md
  documentation/sos-debugging-extension.md
  eng/InstallRuntimes.proj
  eng/Versions.props
  src/Microsoft.Diagnostics.DebugServices/AnalyzeContext.cs
  src/Microsoft.Diagnostics.Repl/Command/Attributes.cs
  src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
  src/SOS/SOS.Hosting/LLDBServices.cs
  src/SOS/SOS.Hosting/SOSHost.cs
  src/SOS/SOS.NETCore/SymbolReader.cs
  src/SOS/Strike/hostcoreclr.cpp
  src/SOS/Strike/hostcoreclr.h
  src/SOS/Strike/sosdocs.txt
  src/SOS/Strike/sosdocsunix.txt
  src/SOS/Strike/strike.cpp
  src/SOS/lldbplugin.tests/t_cmd_pe.py
  src/Tools/dotnet-dump/Analyzer.cs
  src/Tools/dotnet-dump/Commands/SOSCommand.cs
  src/Tools/dotnet-dump/Commands/SOSCommandForWindows.cs
  src/Tools/dotnet-dump/Commands/SetClrPathCommand.cs
  src/inc/palclr.h
Labels: bug

#714 Initial commit for Grape - a testing framework for trace generation on .NET
  src/tests/Grape/Grape.csproj
  src/tests/Grape/Program.cs
  src/tests/Grape/TestRunner.cs
  src/tests/Grape/TraceGeneratorConfiguration.cs
  src/tests/Grape/TraceGenerators/EtwTraceGenerator.cs
  src/tests/Grape/TraceGenerators/EventPipeTraceGenerator.cs
  src/tests/Grape/config.json
Labels: testing
