Repository dotnet/diagnostics, pull requests merged in 2020-04, with the labels that each got.

#973 Report missing DAC error for cross DAC clrstack -i
  src/SOS/Strike/strike.cpp
Labels: auto-merge

#974 Fix description list command
  src/Tools/dotnet-counters/CounterProvider.cs
  src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
  src/Tools/dotnet-counters/KnownData.cs
Labels: dotnet-counters

#979 Converting Log Analytics agent to user deployed agent scenario
  .gitignore
  diagnostics.sln
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/AuthModel.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/AuthenticatingHandler.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/LogAnalyticsLogger.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/LogAnalyticsLoggerProvider.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/LogRestClient.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsLogger.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsModel.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsRestClient.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/Microsoft.Diagnostics.Monitoring.LogAnalytics.csproj
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
  src/Microsoft.Diagnostics.Monitoring.RestServer/appsettings.Development.json
  src/Microsoft.Diagnostics.Monitoring.RestServer/appsettings.json
  src/Microsoft.Diagnostics.Monitoring/Configuration/ContextConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Configuration/MonitoringSourceConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring/Contracts/IMetricsLogger.cs
  src/Microsoft.Diagnostics.Monitoring/Contracts/Metric.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring/Dumper.Windows.cs
  src/Microsoft.Diagnostics.Monitoring/Logging/LogObject.cs
  src/Microsoft.Diagnostics.Monitoring/Logging/LogValuesFormatter.cs
  src/Microsoft.Diagnostics.Monitoring/Logging/LoggerException.cs
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: dotnet-monitor

#961 Initial commit DacCompareNativeTypes
  src/tests/DacCompareNativeTypes/DacCompareNativeTypes.csproj
  src/tests/DacCompareNativeTypes/DwarfParse.cs
  src/tests/DacCompareNativeTypes/Member.cs
  src/tests/DacCompareNativeTypes/PdbParser.cs
  src/tests/DacCompareNativeTypes/Program.cs
  src/tests/DacCompareNativeTypes/Readme.md
  src/tests/DacCompareNativeTypes/Type.cs
  src/tests/DacCompareNativeTypes/Whitespace.cs
Labels: auto-merge

#1000 Fix eeheap output on 32-bit targets
  src/SOS/Strike/eeheap.cpp
Labels: auto-merge

#1003 Reduce the default buffer size requested for counter session to 10MB
  src/Tools/dotnet-counters/CounterMonitor.cs
Labels: dotnet-counters

#1008 Fix links to Code of Conduct
  README.md
Labels: auto-merge

#1006 Properly sign Netonsoft DLLs
  eng/Signing.props
Labels: engineering

#1024 Remove https binding for now
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
Labels: dotnet-monitor

#1033 Parameterize binding urls. This is to enable local docker scenarios.
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/Program.cs
Labels: dotnet-monitor

#1036 Cross dbi
  src/SOS/Strike/cordebugdatatarget.h
  src/SOS/Strike/runtime.cpp
  src/SOS/debugshim/debugshim.cpp
  src/SOS/debugshim/debugshim.h
  src/Tools/dotnet-dump/Analyzer.cs
Labels: auto-merge, dotnet-dump, dotnet-sos

#1047 Enable SDL required warnings
  src/SOS/Strike/ExpressionNode.cpp
  src/SOS/Strike/util.h
  src/inc/warningcontrol.h
  src/pal/inc/pal.h
Labels: auto-merge

#1048 Update clrmd to fix dotnet-dump module enum perf.
  eng/Versions.props
  src/SOS/SOS.Hosting/dbgeng/DebugAdvanced.cs
  src/SOS/SOS.Hosting/dbgeng/DebugClient.cs
  src/SOS/SOS.Hosting/dbgeng/DebugControl.cs
  src/SOS/SOS.Hosting/dbgeng/DebugDataSpaces.cs
  src/SOS/SOS.Hosting/dbgeng/DebugRegisters.cs
  src/SOS/SOS.Hosting/dbgeng/DebugSymbols.cs
  src/SOS/SOS.Hosting/dbgeng/DebugSystemObjects.cs
  src/SOS/Strike/strike.cpp
  src/Tools/dotnet-dump/Commands/ClrModulesCommand.cs
Labels: auto-merge

#1044 Enable roslyn analyzers
  eng/Analyzers.props
  eng/CodeAnalysis.Repository.ruleset
  eng/CodeAnalysis.Security.ruleset
  eng/CodeAnalysis.ruleset
  src/Directory.Build.props
  src/Microsoft.Diagnostics.Monitoring/Logging/LogValuesFormatter.cs
  src/Microsoft.Diagnostics.Monitoring/Logging/LoggerException.cs
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSessionConfiguration.cs
  src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
  src/SOS/SOS.Hosting/SOSHost.cs
  src/Tools/dotnet-dump/Program.cs
  src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs
  src/tests/eventpipe/common/IpcTraceTest.cs
Labels: auto-merge

#791 dotnet-gcdump: report verb
  .gitignore
  src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
  src/Tools/dotnet-gcdump/CommandLine/PrintReportHelper.cs
  src/Tools/dotnet-gcdump/CommandLine/ReportCommandHandler.cs
  src/Tools/dotnet-gcdump/Program.cs
Labels: dotnet-gcdump

#1052 Rewrite packaging props to enable sharing with single-file tools story
  src/Directory.Build.targets
  src/sos-packaging.props
Labels: engineering

#1055 Fix licensing to be standard MIT across the repo
  Directory.Build.props
  THIRD-PARTY-NOTICES.TXT
  eng/Versions.props
  src/Directory.Build.props
  src/Microsoft.Diagnostics.DebugServices/Microsoft.Diagnostics.DebugServices.csproj
  src/Microsoft.Diagnostics.Repl/Microsoft.Diagnostics.Repl.csproj
  src/Microsoft.Diagnostics.TestHelpers/Microsoft.Diagnostics.TestHelpers.csproj
  src/Microsoft.Diagnostics.TestHelpers/Xunit.Extensions/license.txt
  src/SOS/SOS.Hosting/SOS.Hosting.csproj
  src/SOS/SOS.InstallHelper/SOS.InstallHelper.csproj
  src/SOS/SOS.NETCore/SOS.NETCore.csproj
  src/SOS/SOS.Package/SOS.Package.csproj
  src/SOS/SOS.Package/SOS.Symbol.Package.csproj
  src/SOS/SOS.UnitTests/Debuggees/Directory.Build.props
  src/SOS/SOS.UnitTests/SOS.UnitTests.csproj
  src/SOS/lldbplugin.tests/TestDebuggee/TestDebuggee.csproj
  src/Tools/Directory.Build.props
Labels: auto-merge

#1061 Servicing testing fixes
  diagnostics.yml
  eng/build.yml
Labels: auto-merge, engineering

#1056 Use DateTime.Now instead of Stopwatch.GetTimestamp()
  src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs
Labels: auto-merge, dotnet-gcdump

#1080 Add threadpool command to xplat SOS/dotnet-dump
  src/SOS/Strike/sos_unixexports.src
  src/SOS/Strike/sosdocs.txt
  src/SOS/Strike/sosdocsunix.txt
  src/SOS/Strike/strike.cpp
  src/SOS/lldbplugin/soscommand.cpp
  src/Tools/dotnet-dump/Commands/SOSCommand.cs
Labels: auto-merge

#1081 Revise DacCompareNativeTypes
  src/tests/DacCompareNativeTypes/Program.cs
Labels: auto-merge

#1073 Add helper classes for consuming Eventpipe data
  diagnostics.sln
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/OutputStreamResult.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/StreamWithCleanupResult.cs
  src/Microsoft.Diagnostics.Monitoring/Configuration/ContextConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Configuration/CpuProfileConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Configuration/LoggingSourceConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Configuration/MetricSourceConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Configuration/MonitoringSourceConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticsEventPipeProcessor.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticsMonitor.cs
  src/Microsoft.Diagnostics.Monitoring/Logging/StreamingLogger.cs
  src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/Startup.cs
  src/tests/dotnet-monitor/DiagnosticsMonitorTests.cs
  src/tests/dotnet-monitor/DotnetMonitor.UnitTests.csproj
  src/tests/dotnet-monitor/RemoteTestExecution.cs
Labels: dotnet-monitor

#1091 Fix EventPipeProvider to enable listening to events without keyword
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeProvider.cs
  src/tests/eventpipe/CustomEvents.cs
Labels: Microsoft.Diagnostics.NETCore.Client
