Repository dotnet/diagnostics, pull requests merged in 2020-03, with the labels that each got.

#852 Pipeline consolidation, added SDL and signature verification.
  .vsts-dotnet-ci.yml
  .vsts-dotnet.yml
  diagnostics.yml
  documentation/design-docs/dotnet-tools.md
  documentation/tutorial/README.md
  documentation/tutorial/app_is_leaking_memory_eventual_crash.md
  documentation/tutorial/hung_app.md
  eng/build.yml
  eng/common-variables.yml
  src/Microsoft.Diagnostics.TestHelpers/TestStep.cs
  src/SOS/Strike/util.h
  src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs
  src/pal/src/locale/UnicodeData.txt
Labels: auto-merge

#874 Update build.yml to use OSX 10.14
  eng/build.yml
  src/SOS/SOS.UnitTests/Scripts/lldbhelper.py
Labels: engineering

#878 Create dotnet-monitor tool
  diagnostics.sln
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/AuthModel.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/AuthenticatingHandler.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/LogAnalyticsLogger.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/LogAnalyticsLoggerProvider.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/LogRestClient.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsLogger.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsModel.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/MetricsRestClient.cs
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/Microsoft.Diagnostics.Monitoring.LogAnalytics.csproj
  src/Microsoft.Diagnostics.Monitoring/ContextConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticsMonitor.cs
  src/Microsoft.Diagnostics.Monitoring/IMetricsLogger.cs
  src/Microsoft.Diagnostics.Monitoring/LogObject.cs
  src/Microsoft.Diagnostics.Monitoring/LogValuesFormatter.cs
  src/Microsoft.Diagnostics.Monitoring/LoggerException.cs
  src/Microsoft.Diagnostics.Monitoring/Metric.cs
  src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
  src/Microsoft.Diagnostics.Monitoring/MonitoringSourceConfiguration.cs
  src/Tools/dotnet-monitor/ConsoleMetricsLogger.cs
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
  src/Tools/dotnet-monitor/runtimeconfig.template.json
Labels: dotnet-monitor

#889 Fix several issues in build and publishing
  diagnostics.yml
  eng/Build-Native.cmd
  eng/common-variables.yml
  src/Directory.Build.targets
  src/Microsoft.Diagnostics.DebugServices/Microsoft.Diagnostics.DebugServices.csproj
  src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
  src/Microsoft.Diagnostics.Repl/Microsoft.Diagnostics.Repl.csproj
  src/Microsoft.Diagnostics.TestHelpers/Microsoft.Diagnostics.TestHelpers.csproj
  src/SOS/SOS.NETCore/SOS.NETCore.csproj
  src/SOS/SOS.Package/SOS.Package.csproj
  src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
  src/SOS/SOS.UnitTests/SOS.UnitTests.csproj
  src/Tools/Directory.Build.props
  src/Tools/dotnet-dump/dotnet-dump.csproj
Labels: auto-merge, engineering

#891 Change dotnet-monitor tool to non-shipping temporarily
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.LogAnalytics/Microsoft.Diagnostics.Monitoring.LogAnalytics.csproj
  src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: auto-merge, dotnet-monitor

#897 Revert "[master] Update dependencies from dotnet/aspnetcore (#886)"
  eng/Version.Details.xml
  eng/Versions.props
Labels: auto-merge, engineering

#898 Add darc dependency to symstore
  eng/Version.Details.xml
  eng/Versions.props
Labels: auto-merge

#894 [dotnet trace] Add Chromium Trace Event file format to list of supported formats
  eng/Versions.props
  src/Tools/dotnet-trace/TraceFileFormatConverter.cs
Labels: dotnet-trace

#906 Remove checking for python
  CMakeLists.txt
Labels: auto-merge

#915 Add .NET Core hosting location file support
  src/SOS/Strike/hostcoreclr.cpp
Labels: auto-merge

#918 Update to clrmd 1.1.116301
  eng/Versions.props
Labels: auto-merge

#927 [dotnet-dump] Allow Linux core dumps to be loaded on WIndows
  src/Tools/dotnet-dump/Analyzer.cs
Labels: auto-merge

#934 Disable Microsoft.Diagnostics.NETCore.Client.WriteAllDumpTypesTest
  src/tests/Microsoft.Diagnostics.NETCore.Client/WriteDumpTests.cs
Labels: auto-merge

#809 dotnet-gcdump: Update docs to include print verb
  documentation/design-docs/dotnet-tools.md
Labels: dotnet-gcdump
