Repository dotnet/diagnostics, pull requests merged in 2020-09, with the labels that each got.

#1521 Bump dotnet-monitor to 5.0.0-preview.3.*
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: dotnet-monitor

#1490 General Test Improvements
  src/tests/Microsoft.Diagnostics.NETCore.Client/CommonHelper.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessEnvironmentTests.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/GetPublishedProcessesTests.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.UnitTests.csproj
  src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerHelper.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/TestRunner.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/WriteDumpTests.cs
  src/tests/dotnet-monitor/DiagnosticsMonitorTests.cs
  src/tests/dotnet-monitor/EndpointInfoSourceTests.cs
Labels: auto-merge, testing

#1525 Add dependencies on CLRMD and SDK
  eng/Version.Details.xml
  eng/Versions.props
  src/SOS/SOS.Hosting/SOS.Hosting.csproj
Labels: auto-merge, engineering

#1481 Add more reversed server APIs for parity between async and non-async methods
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs
  src/Microsoft.Diagnostics.NETCore.Client/HandleableCollection.cs
  src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/HandleableCollectionTests.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
  src/tests/dotnet-monitor/EndpointInfoSourceTests.cs
Labels: Microsoft.Diagnostics.NETCore.Client, enhancement

#1550 Third Party Sign parallel stacks
  eng/Signing.props
Labels: auto-merge

#1553 Enable building SOS on Apple Silicon
  CMakeLists.txt
  eng/build.sh
  src/pal/inc/pal.h
  src/pal/inc/unixasmmacrosarm64.inc
  src/pal/src/CMakeLists.txt
  src/pal/src/arch/arm64/context.S
Labels: arm64, dotnet-dump, dotnet-sos, sos

#1497 use alignlarge for poh in gcheaptraverse
  src/SOS/Strike/eeheap.cpp
Labels: sos

#1559 Enable osx-arm64 cross compilation
  compileoptions.cmake
  eng/build.sh
  src/pal/src/CMakeLists.txt
Labels: arm64

#1571 Disable eeversion test for Alpine
  src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
  src/SOS/SOS.UnitTests/Scripts/StackTests.script
Labels: auto-merge

#1575 Update outdated list-processes command on diagnostics tutorials doc
  documentation/tutorial/app_is_leaking_memory_eventual_crash.md
  documentation/tutorial/app_running_slow_highcpu.md
  documentation/tutorial/hung_app.md
  documentation/tutorial/intermittent_memory_spike.md
Labels: documentation

#1533 Enable createdump/dotnet-dump testing on MacOS
  .gitignore
  eng/CleanupPrivateBuild.csproj
  eng/CreateVersionFile.csproj
  eng/InstallRuntimes.proj
  eng/dotnet-install.ps1
  eng/dotnet-install.sh
  global.json
  src/Microsoft.Diagnostics.TestHelpers/DotNetBuildDebuggeeTestStep.cs
  src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
  src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
  src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
  src/SOS/SOS.UnitTests/Debuggees/DesktopClrHost/CMakeLists.txt
  src/SOS/SOS.UnitTests/Debuggees/DivZero/DivZero.csproj
  src/SOS/SOS.UnitTests/Debuggees/GCPOH/GCPOH.csproj
  src/SOS/SOS.UnitTests/Debuggees/GCWhere/GCWhere.csproj
  src/SOS/SOS.UnitTests/Debuggees/LineNums/LineNums.csproj
  src/SOS/SOS.UnitTests/Debuggees/NestedExceptionTest/NestedExceptionTest.csproj
  src/SOS/SOS.UnitTests/Debuggees/Overflow/Overflow.csproj
  src/SOS/SOS.UnitTests/Debuggees/ReflectionTest/ReflectionTest.csproj
  src/SOS/SOS.UnitTests/Debuggees/SimpleThrow/SimpleThrow.csproj
  src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestApp/SymbolTestApp.csproj
  src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestDll/SymbolTestDll.csproj
  src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/RandomUserLibrary/RandomUserLibrary.csproj
  src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/TaskNestedException/TaskNestedException.csproj
  src/SOS/SOS.UnitTests/Debuggees/WebApp3/Program.cs
  src/SOS/SOS.UnitTests/Debuggees/WebApp3/WebApp3.csproj
  src/SOS/SOS.UnitTests/Debuggees/WebApp3/testCert.pfx
  src/SOS/SOS.UnitTests/SOS.UnitTests.csproj
  src/SOS/SOS.UnitTests/SOS.cs
  src/SOS/SOS.UnitTests/SOSRunner.cs
  src/SOS/Strike/strike.cpp
Labels: auto-merge

#1581 Fix GetDefaultValue func
  src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Labels: auto-merge, dotnet-trace

#1544 Single File Bundles
  diagnostics.yml
  eng/Build.props
  eng/Publishing.props
  eng/Signing.props
  eng/build.ps1
  eng/cipack.cmd
  global.json
  src/Directory.Build.props
  src/Tools/Directory.Build.props
  src/Tools/Directory.Build.targets
  src/Tools/dotnet-counters/dotnet-counters.csproj
  src/Tools/dotnet-dump/dotnet-dump.csproj
  src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
  src/Tools/dotnet-sos/dotnet-sos.csproj
  src/Tools/dotnet-trace/dotnet-trace.csproj
  src/singlefile-tools.proj
Labels: auto-merge

#1597 Fix incorrect cpu-usage description
  src/Tools/dotnet-counters/KnownData.cs
Labels: dotnet-counters

#1596 Get command line, process name, os, process architecture, and process environment.
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsService.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Models/ProcessIdentifierModel.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Models/ProcessModel.cs
  src/Microsoft.Diagnostics.Monitoring/ClientEndpointInfoSource.cs
  src/Microsoft.Diagnostics.Monitoring/CommandLineHelper.cs
  src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring/Contracts/IEndpointInfoSource.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
  src/Microsoft.Diagnostics.Monitoring/DiagnosticsEventPipeProcessor.cs
  src/Microsoft.Diagnostics.Monitoring/EndpointInfo.cs
  src/Microsoft.Diagnostics.Monitoring/ServerEndpointInfoSource.cs
  src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/IpcEndpointInfo.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerHelper.cs
  src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
  src/tests/dotnet-monitor/CommandLineHelperTests.cs
  src/tests/dotnet-monitor/EndpointInfoSourceTests.cs
Labels: dotnet-monitor, enhancement

#1608 Fix testing on arm64.
  eng/InstallRuntimes.proj
  eng/Versions.props
  src/Microsoft.Diagnostics.DebugServices/ThreadService.cs
  src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
  src/SOS/SOS.UnitTests/Scripts/DivZero.script
  src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
  src/SOS/SOS.UnitTests/Scripts/StackTests.script
  src/SOS/SOS.UnitTests/Scripts/WebApp.script
  src/SOS/Strike/ExpressionNode.cpp
  src/SOS/Strike/cordebugdatatarget.h
  src/SOS/Strike/datatarget.cpp
  src/SOS/Strike/disasm.h
  src/SOS/Strike/disasmARM.cpp
  src/SOS/Strike/disasmX86.cpp
  src/SOS/Strike/exts.h
  src/SOS/Strike/strike.cpp
  src/SOS/Strike/util.cpp
  src/inc/dbgtargetcontext.h
Labels: auto-merge

#1604 Add issue templates and code owners
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/01_Bug_Report.md
  .github/ISSUE_TEMPLATE/02_Feature_Request.md
  .github/ISSUE_TEMPLATE/03_Documentation_Request.md
  .github/ISSUE_TEMPLATE/04_Blank_Issue.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: auto-merge

#1620 Fix issues with single-file and hash generation
  diagnostics.yml
  eng/AfterSigning.targets
  eng/Publishing.props
  eng/build.ps1
  eng/ci-prepare-artifacts.cmd
  eng/cipack.cmd
  src/Tools/Directory.Build.targets
Labels: auto-merge, engineering
