Repository dotnet/diagnostics, pull requests merged in 2021-01, with the labels that each got.

#1843 Add EventPipeStress framework
  src/tests/EventPipeStress/Common/BurstPattern.cs
  src/tests/EventPipeStress/Common/Common.csproj
  src/tests/EventPipeStress/Common/Options.cs
  src/tests/EventPipeStress/Orchestrator/CommandLine.cs
  src/tests/EventPipeStress/Orchestrator/Orchestrator.csproj
  src/tests/EventPipeStress/Orchestrator/Program.cs
  src/tests/EventPipeStress/Orchestrator/TestResult.cs
  src/tests/EventPipeStress/README.md
  src/tests/EventPipeStress/Stress/Program.cs
  src/tests/EventPipeStress/Stress/Stress.csproj
Labels: testing

#1888 "ps" command handler fix
  src/Tools/Common/Commands/ProcessStatus.cs
Labels: bug

#1897 The cdb-sos package moved to a different feed
  NuGet.config
Labels: auto-merge

#1873 Logging improvements for dotnet-monitor
  src/Microsoft.Diagnostics.Monitoring.RestServer/ActionContextExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/ArtifactMetadataNames.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagControllerExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/MetricsController.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/EgressStreamResult.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/KeyValueLogScope.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/KeyValueLogScopeExtensions.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/OutputStreamResult.cs
  src/Microsoft.Diagnostics.Monitoring.RestServer/appsettings.json
  src/Tools/dotnet-monitor/ActivityExtensions.cs
  src/Tools/dotnet-monitor/ActivityMetadataNames.cs
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs
  src/Tools/dotnet-monitor/Egress/AzureBlobEgressFactory.cs
  src/Tools/dotnet-monitor/Egress/Configuration/EgressConfigureOptions.cs
  src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressProvider.cs
  src/Tools/dotnet-monitor/ExperimentalToolLogger.cs
  src/Tools/dotnet-monitor/Program.cs
  src/Tools/dotnet-monitor/Startup.cs
Labels: dotnet-monitor, enhancement

#1903 Update console logger and set content root.
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.RestServer/appsettings.json
  src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
  src/Tools/dotnet-monitor/dotnet-monitor.csproj
Labels: dotnet-monitor, enhancement

#1905 Update log scope to be more compatible with JSON console logger.
  src/Microsoft.Diagnostics.Monitoring.RestServer/KeyValueLogScope.cs
Labels: dotnet-monitor, enhancement

#1878 Update TraceEvent
  eng/Versions.props
Labels: engineering

#1930 Misc interface and implementation changes
  NuGet.config
  documentation/FAQ.md
  src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleService.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleServiceFromDataReader.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/Runtime.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeService.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/Thread.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/ThreadService.cs
  src/Microsoft.Diagnostics.DebugServices.Implementation/ThreadServiceFromDataReader.cs
  src/Microsoft.Diagnostics.DebugServices/IExportSymbols.cs
  src/Microsoft.Diagnostics.DebugServices/IHost.cs
  src/Microsoft.Diagnostics.DebugServices/IModule.cs
  src/Microsoft.Diagnostics.DebugServices/IModuleSymbols.cs
  src/Microsoft.Diagnostics.DebugServices/IRuntimeService.cs
  src/Microsoft.Diagnostics.DebugServices/ISymbolService.cs
  src/Microsoft.Diagnostics.DebugServices/IThread.cs
  src/Microsoft.Diagnostics.DebugServices/IThreadService.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Host/ModulesCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Host/RegistersCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimesCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Host/ThreadsCommand.cs
  src/SOS/SOS.Extensions/DebuggerServices.cs
  src/SOS/SOS.Extensions/HostServices.cs
  src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
  src/SOS/SOS.Extensions/ThreadServiceFromDebuggerServices.cs
  src/SOS/SOS.Hosting/CorDebugDataTargetWrapper.cs
  src/SOS/SOS.Hosting/DataTargetWrapper.cs
  src/SOS/SOS.Hosting/LLDBServices.cs
  src/SOS/SOS.Hosting/SOSHost.cs
  src/SOS/SOS.Hosting/SymbolServiceWrapper.cs
  src/SOS/Strike/dbgengservices.cpp
  src/SOS/Strike/dbgengservices.h
  src/SOS/Strike/exts.cpp
  src/SOS/Strike/strike.cpp
  src/SOS/inc/debuggerservices.h
  src/SOS/lldbplugin/services.cpp
  src/SOS/lldbplugin/services.h
  src/SOS/lldbplugin/soscommand.cpp
  src/Tools/dotnet-dump/Analyzer.cs
Labels: auto-merge
