Repository dotnet/diagnostics, pull requests merged in 2021-05, with the labels that each got.

#2253 dotnet-dump analyze allow hex-addresses with and w/o 0x prefix
  src/Microsoft.Diagnostics.DebugServices/CommandBase.cs
  src/Tools/dotnet-dump/Commands/ReadMemoryCommand.cs
Labels: auto-merge

#2256 Skip logs pipeline test on Windows.
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
Labels: auto-merge

#2274 Add FilterSpecs to EventLogsPipeline
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LogMessageType.cs
  src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LoggingSourceConfiguration.cs
  src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
  src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipelineSettings.cs
  src/tests/EventPipeTracee/Program.cs
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.csproj
  src/tests/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.UnitTests.csproj
Labels: enhancement, testing

#2273 Stop pipelines in tests after receiving expected events.
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterPipelineUnitTests.cs
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventTracePipelineUnitTests.cs
  src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/PipelineTestUtilities.cs
Labels: testing

#2286 Update test runtimes to 2.1.28, 3.1.15, 5.0.6
  eng/Versions.props
  src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
Labels: auto-merge

#2312 Fix terminology
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
Labels: auto-merge
