Repository dotnet/diagnostics, pull requests merged in 2021-04, with the labels that each got.

#2092 Change default trace name to app name + timestamp
  documentation/dotnet-trace-instructions.md
  src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Labels: dotnet-trace, enhancement

#2138 Revert "Temporarily disable the failing Windows x64 debug builds (#2113)"
  diagnostics.yml
Labels: auto-merge

#2176 Add LayoutWorker that can block files from publishing
  eng/release/DiagnosticsReleaseTool/Common/FileIgnoreWorker.cs
Labels: engineering

#2187 Use MacOS coredump special thread info
  diagnostics.sln
  eng/Version.Details.xml
  eng/Versions.props
  src/SOS/SOS.UnitTests/SOS.cs
  src/SOS/SOS.UnitTests/SOSRunner.cs
  src/SOS/inc/specialthreadinfo.h
  src/SOS/lldbplugin/services.cpp
  src/SOS/lldbplugin/services.h
  src/SOS/lldbplugin/setsostidcommand.cpp
  src/SOS/lldbplugin/sosplugin.h
Labels: auto-merge

#2211 Update packages with security patches
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
  src/SOS/SOS.UnitTests/Debuggees/WebApp/WebApp.csproj
Labels: auto-merge
