Repository dotnet/diagnostics, pull requests merged in 2023-10, with the labels that each got.

#4199 Improve dotnet-dsrouter log levels and info.
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
  src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
  src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
  src/Tools/dotnet-dsrouter/Program.cs
Labels: ds-router

#4318 !maddress misattributes memory to the GC
  src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
Labels: bug, sos

#4325 Additional !maddress fixes
  src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
Labels: bug, sos

#4361 Restore error message when the heap isn't walkable
  src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
Labels: bug, sos

#4379 Allow ` in hex strings
  src/Microsoft.Diagnostics.DebugServices/CommandBase.cs
  src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/EEHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/HeapWithFilters.cs
  src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
Labels: bug, auto-merge, sos
