Repository dotnet/diagnostics, pull requests merged in 2023-01, with the labels that each got.

#3475 Port GCDump fixes from PerfView
  eng/Versions.props
  src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
  src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapInfo.cs
  src/Tools/dotnet-gcdump/DotNetHeapDump/GCHeapDump.cs
  src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs
  src/Tools/dotnet-gcdump/DotNetHeapDump/MemoryGraph.cs
Labels: dotnet-gcdump

#3588 Change tool TFMs to net6.0 and drop 3.1 hosting support
  eng/AuxMsbuildFiles/SdkPackOverrides.targets
  eng/Build-Native.cmd
  eng/CleanupPrivateBuild.csproj
  eng/CleanupPrivateBuild.proj
  eng/CreateVersionFile.proj
  eng/InstallRuntimes.proj
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Versions.props
  eng/build.ps1
  eng/build.sh
  eng/configure-toolset.ps1
  eng/configure-toolset.sh
  global.json
  src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
  src/Microsoft.Diagnostics.TestHelpers/AcquireDotNetTestStep.cs
  src/Microsoft.Diagnostics.TestHelpers/CliDebuggeeCompiler.cs
  src/Microsoft.Diagnostics.TestHelpers/Microsoft.Diagnostics.TestHelpers.csproj
  src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
  src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
  src/SOS/SOS.UnitTests/Debuggees/DesktopClrHost/CMakeLists.txt
  src/SOS/SOS.UnitTests/Debuggees/Directory.Build.props
  src/SOS/extensions/hostcoreclr.cpp
  src/SOS/lldbplugin.tests/TestDebuggee/TestDebuggee.csproj
  src/Tools/Directory.Build.props
  src/Tools/dotnet-counters/dotnet-counters.csproj
  src/Tools/dotnet-dump/dotnet-dump.csproj
  src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
  src/Tools/dotnet-sos/dotnet-sos.csproj
  src/Tools/dotnet-stack/dotnet-stack.csproj
  src/Tools/dotnet-trace/CommandLine/PrintReportHelper.cs
  src/Tools/dotnet-trace/dotnet-trace.csproj
  src/singlefile-tools.proj
  src/tests/CommonTestRunner/CommonTestRunner.csproj
  src/tests/CommonTestRunner/ConfigFiles/Unix/Debugger.Tests.Config.txt
  src/tests/CommonTestRunner/ConfigFiles/Windows/Debugger.Tests.Config.txt
  src/tests/DacCompareNativeTypes/DacCompareNativeTypes.csproj
  src/tests/Directory.Build.props
  src/tests/EventPipeTracee/EventPipeTracee.csproj
  src/tests/ExitCodeTracee/ExitCodeTracee.csproj
  src/tests/Grape/Grape.csproj
  src/tests/StackTracee/StackTracee.csproj
  src/tests/Tracee/Tracee.csproj
  src/tests/benchmarks/benchmarks.csproj
Labels: auto-merge

#3083 Dev/mirogers/kudu console
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
  src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClientExceptions.cs
  src/Tools/Common/Commands/ProcessStatus.cs
Labels: dotnet-trace, dotnet-counters, dotnet-dump, dotnet-stack
