Repository dotnet/diagnostics, pull requests merged in 2023-04, with the labels that each got.

#3800 Fix IndexOutOfRangeException
  src/SOS/SOS.Extensions/MemoryRegionServiceFromDebuggerServices.cs
Labels: auto-merge

#3803 Add maddress -orderBySize
  src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
Labels: enhancement, auto-merge

#3804 Update ClrMD version
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.Diagnostics.ExtensionCommands/ExtensionMethodHelpers.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FindEphemeralReferencesToLOHCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FindReferencesToEphemeralCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCHeapStatCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCWhereCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Generation.cs
  src/Microsoft.Diagnostics.ExtensionCommands/SizeStatsCommand.cs
Labels: auto-merge

#3819 Update Logging and AsyncInterfaces versions
  eng/Versions.props
  src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
  src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
Labels: auto-merge

#3811 Reimplement !verifyobj and !dumpruntimetypes
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.Diagnostics.ExtensionCommands/DumpObjGCRefsHelper.cs
  src/Microsoft.Diagnostics.ExtensionCommands/DumpRuntimeTypeCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/ExtensionMethodHelpers.cs
  src/Microsoft.Diagnostics.ExtensionCommands/TableOutput.cs
  src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/VerifyObjectCommand.cs
  src/SOS/SOS.Hosting/Commands/SOSCommand.cs
  src/SOS/SOS.UnitTests/Scripts/GCTests.script
  src/SOS/Strike/eeheap.cpp
  src/SOS/Strike/gcroot.cpp
  src/SOS/Strike/sos.cpp
  src/SOS/Strike/sos.h
  src/SOS/Strike/strike.cpp
  src/SOS/Strike/util.h
  src/SOS/lldbplugin/soscommand.cpp
Labels: bug, enhancement, auto-merge

#3835 Update ClrMD
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.Diagnostics.ExtensionCommands/EEHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
  src/Microsoft.Diagnostics.ExtensionCommands/ThreadPoolCommand.cs
Labels: auto-merge

#3816 Fix incorrect rendering of counters
  src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
Labels: dotnet-counters, auto-merge

#3844 Remove BOM marker from the middle of !traversexml
  src/Microsoft.Diagnostics.ExtensionCommands/TraverseHeapCommand.cs
Labels: bug, auto-merge, sos

#3535 Update docker images to latest tags
  diagnostics.yml
  eng/build.yml
  eng/cibuild.sh
  src/SOS/SOS.UnitTests/SOSRunner.cs
Labels: DO NOT MERGE

#3852 Fit and Finish: Clean up SOS command table output
  src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapService.cs
  src/Microsoft.Diagnostics.ExtensionCommands/DumpObjGCRefsHelper.cs
  src/Microsoft.Diagnostics.ExtensionCommands/DumpRuntimeTypeCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/DumpStackObjectsCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/EEHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FinalizeQueueCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FindEphemeralReferencesToLOHCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FindPointersInCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FindReferencesToEphemeralCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCHeapStatCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCRootCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCToNativeCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCWhereCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/ListNearObjCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/Align.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/BorderedTable.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/Column.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/ColumnKind.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/Dml.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/DmlFormat.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/Format.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/Formats.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/StringBuilderPool.cs
  src/Microsoft.Diagnostics.ExtensionCommands/Output/Table.cs
  src/Microsoft.Diagnostics.ExtensionCommands/SimulateGCHeapCorruption.cs
  src/Microsoft.Diagnostics.ExtensionCommands/SizeStatsCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/TableOutput.cs
  src/Microsoft.Diagnostics.ExtensionCommands/ThreadPoolCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/VerifyObjectCommand.cs
  src/SOS/SOS.Extensions/ConsoleServiceFromDebuggerServices.cs
  src/SOS/SOS.UnitTests/Scripts/ConcurrentDictionaries.script
Labels: enhancement, auto-merge, sos
