Repository dotnet/diagnostics, pull requests merged in 2023-02, with the labels that each got.

#3628 Cap node processing at 10mil and log issue
  src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
Labels: dotnet-gcdump

#3647 Add native memory analysis helper commands
  src/Microsoft.Diagnostics.DebugServices/IMemoryRegion.cs
  src/Microsoft.Diagnostics.DebugServices/IMemoryRegionService.cs
  src/Microsoft.Diagnostics.DebugServices/IModuleSymbols.cs
  src/Microsoft.Diagnostics.ExtensionCommands/ClrMemoryPointer.cs
  src/Microsoft.Diagnostics.ExtensionCommands/ExtensionMethodHelpers.cs
  src/Microsoft.Diagnostics.ExtensionCommands/FindPointersInCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/GCToNativeCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
  src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
  src/Microsoft.Diagnostics.ExtensionCommands/TableOutput.cs
  src/SOS/SOS.Extensions/DbgEngOutputHolder.cs
  src/SOS/SOS.Extensions/DebuggerServices.cs
  src/SOS/SOS.Extensions/HostServices.cs
  src/SOS/SOS.Extensions/MemoryRegionServiceFromDebuggerServices.cs
  src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
  src/SOS/Strike/dbgengservices.cpp
Labels: enhancement

#3666 maddress: Work around .Net 7 LoaderHeap traversal issue
  src/Microsoft.Diagnostics.ExtensionCommands/ClrMemoryPointer.cs
  src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
Labels: bug

#3692 Fix build target architecture passing
  eng/build.sh
Labels: auto-merge
